spring.application.name=gomokuService
server.port=8080
spring.web.socket.servlet.enabled=true

logging.level.com.elut111.gomokuservice=INFO
logging.level.org.springframework.web.socket=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n

server.tomcat.max-connections=1000
server.tomcat.threads.max=200
server.tomcat.accept-count=100